name: "JS Hangman"
description: "A hangman game I made"

#url: "http://127.0.0.1:4000/"
url: "http://kalenenc.github.io/js-hangman/"

#paginate: 10

markdown: kramdown
permalink: pretty
# highlighter: pygments